# Generated by Django 3.2.25 on 2026-05-04 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='active_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='session',
            name='idle_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
