# Generated by Django 3.2.25 on 2026-05-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20260504_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_ping_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
