# Generated by Django 6.0.5 on 2026-05-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_company_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
